### ISSUE TITLE
The Big Post Demo1 TODO list

### ISSUE THREAD

**Issue by Skull220** [Skull220/On-Your-Hands#12]
- [x] Have Redirector boxes line trace for the floor instead of using tags
- [x] Fix esc not exiting the codex
- [x] Fix crosshair code so that it'd color like the laser pointer does; and so magic fires from the center
- [x] Add tooltips for settings items that are missing them
- [x] Add circular indicator for Purple magic
- [x] Fix it so resolution isn't directly tied to video mode
- [x] Fix bug where color on laser pointer is inaccurate to the current magic type
- [x] Add an image to the brightness slider
- [x] Add colorblind options
- [x] Add 'view colorblind chart' option
- [x] Add items to codex
- [x] Find a better way to prevent firing other than object-held for things that aren't literally an object being held
- [x] Add one-way walls for softlock proofing
- [x] Vsync toggle
- [x] Add a level select
- [x] Add a "use" indicator for objects that can be used
- [x] Settle on a way of handling Indigo Magic physics so redirector boxes won't be shoved in walls
~~ Build level 24~~
- [ ] Write a final plotline for the game including locations and events
- [x] Write the alien lore 
- [x] Write the humanity lore 
- [ ] #90
- [x] Discord Rich Presence Integration
- [x] Rewrite audio logs to focus less on tutorializing
- [ ] #91
- [x] Further serialize the checkpoint system if possible
- [x] Fully code the Grinder's AI so it's not just MoveTo all the time
- [ ] Rewrite all code to bring it up to current standards
- [ ] Multi-threading
- [ ] Maybe! come up with a more interesting idea for Orange, Green, and/or Red magic
