### ISSUE TITLE
Comprehensive Demo Level 3 To-do list

### ISSUE THREAD

**Issue by Skull220** [Skull220/On-Your-Hands#13]
- [x] Playtest with at 1 other person to verify the puzzles are good
- [x] Playtest with at 1 other person to verify the puzzles are good
- [x] Create Model for the hatch the player pops out of at the beginning
- [x] Find a better way to create a cone effect for the tractor beam
- [x] Connect wires from green buttons to green doors
- [x] Connect wires from orange button to orange doors
- [x] Connect wires from blue button to blue doors
- [x] Connect wires from yellow buttons to yellow doors
- [x] Script the tractor beam to raise the player up and teleport them into the actual level
- [x] Animate the player being raised up 
- [x] Script the door on the left side puzzle to close after the player walks through
- [x] Create a hole in the floor on the right side puzzle instead of lava
- [x] Script the hole in the floor to kill the player if they fall in it 
- [x] Animate the player falling out of the ship
- [x] Add the space skybox
- [x] Place a 1-way wall between the blue and orange doors to prevent softlocking
- [x] Script the middle door to require both green buttons to be held down in order to open 
- [x] find a way to indicate this visually as well, if necessary 
- [x] Come up with a way to make the walls more interesting, possibly by bisecting them and then pushing in the middle lines
- [x] Come up with textures for the walls
- [x] Come up with textures for the ceiling
- [x] Come up with textures for the floor
- [x] Place pipes, 
- [x] wires, 
- [x] and crates around the spaceship for visual flair
- [x] Texture the pipes,
- [x] wires,
- [x] and crates
- [x] Add tables and in other places for more visual flair and believably
- [x] model objects to place on those tables
- [x] Come up with textures for the stairs to make them seem different
- [x] Add chairs,
- [x] consoles, 
- [x] etc into the piloting room 
- [x] Texture the chairs,
- [x] consoles
- [x] etc in the piloting room
- [x] Add a screen into the piloting room
- [x] Add a main console to the piloting room
- [x] Come up with a way to integrate a secret that requires you to remember a door or button
- [x] Come up with a way to integrate a secret that requires creative use of the magics/other mechanics
- [x] See if Jonas will make the Concealer and if we can tease it in a secret
- [x] Redesign the spaceship
- [x] Come up with a good design for the area outside the spaceship
- [x] Place lights in the central room
- [x] Place lights in the left side room
- [x] Place lights in the right side room
- [x] Place lights in the piloting room
