### ISSUE TITLE
The Pre-Demo2 checklist

### ISSUE THREAD

**Issue by Skull220** [Skull220/On-Your-Hands#57]
- [x] Test The Mothership
- [x] Test Chase and Sequence a bit further
- [x] Switch The Mothership and Chase and Sequence to be Map10 and Map09 respectively
- [x] Add Chase and Sequence's start to The Underground Facility's end; add The Mothership's start to Chase and Sequence's end
- [x] Retake Map09's screenshots for RPC and level select
- [x] Add wood supports to Map09's hallways
- [x] ~~Add texture detailing to the inner walls of Map09's button and safe room sections~~
- [x] Animate the Grinder attempting to break through a force field (Map09)
- [x] Animate the hatch closing on the Grinder (Map10)
- [x] Get the ambient noise noise pollution from Strange
- [x] Solidify the writing of the tapes
- [x] Put blue magic special on the X key
- [x] Record Map07 and Map08 tapes with Chip
- [x] Record trailer tape
- [x] Get music from renzo 
- [ ] Put together the trailer
- [x] Write the steam page
- [x] Fix the Lurker in Map07
- [x] Add 'chase' and 'idle' noises to the Grinder
- [x] Add wall break sounds and broken mesh pieces
